### ISSUE TITLE
File name recognition

### ISSUE THREAD

**Issue by davidacrozier** [devgc/GcLinkParser#3]
Files with special characters in the name are erroring out and not represented in the output of GCLinkParser

```
E:\TESTDATA\EXTRACTED\LNKFILES\DBLNKFILES\[ROOT]\PROGRAMDATA\INTEL\EXTREMEGRAPHICS\CUI\RESOURCE\INTEL� HD GRAPHICS.LNK
```

![capture](https://cloud.githubusercontent.com/assets/11384257/19202935/6c5ece52-8c9a-11e6-8e9c-a82ec705514e.PNG)

Using a hex editor, notice the file is recognized as a .lnk file and has the correct header.
![capture](https://cloud.githubusercontent.com/assets/11384257/19203049/f498138c-8c9a-11e6-8017-21e1d3620f02.PNG)

**Comment by devgc** [comment]
Closing this issue. Should be fixed now.

[issue 1](https://github.com/devgc/GcLinkParser/issues/1)
